import { ReactNode } from 'react'

export type ToastVariant = 'default' | 'success' | 'warning' | 'error'

export type ToastPlacement =
  | 'top-left'    | 'top-center'    | 'top-right'
  | 'bottom-left' | 'bottom-center' | 'bottom-right'

export interface ToastOptions {
  id?: string                    // autogenerated when omitted
  title?: ReactNode
  description?: ReactNode
  variant?: ToastVariant
  placement?: ToastPlacement
  duration?: number              // ms – 0 = persist until manual close
  icon?: ReactNode
  action?: {
    label: string
    onClick: () => void
  }
  // allow arbitrary extras for extensibility
  [key: string]: any
}

export interface ToastInternal extends ToastOptions {
  id: string                     // always present after creation
  createdAt: number
  animationState: 'entering' | 'visible' | 'exiting'
}